include/Ark/VM/FFI.hpp
src/VM/FFI/Array.cpp
src/VM/FFI/FFI.cpp
tests/list-tests.ark

This PR adds the reverse FFI for lists (one of the subgoals of #23) and simple tests to check the correctness of the builtin.
Any feedback would be highly appreciated.

Added list reverse FFI

---

include/Ark/VM/Closure.hpp
include/Ark/VM/Frame.hpp
include/Ark/VM/VM.inl
include/Ark/VM/Value.hpp

Needed for #23 (to use std::sort)

Feat value ordering

---

.dockerignore
Dockerfile
docker-entrypoint.sh

Added a few files to have the ability create a Docker image. I recommend adding the `docker build` and `docker push` commands to the pipeline.

Add Dockerfile

---

examples/quicksort.ark
src/VM/VM.cpp

…depending on the object, if the given value was too small
closes #150

fixing #150, firstOf, headOf and tailOf now return [] or an empty string

---

README.md

Changed 
1. "Term"  to "Terms"  
2. "object oriented"  to "object-oriented"
3. "less" to "fewer"

Updated Readme for Effective Reading

---

src/main.cpp

Adds -e/--eval parameters to the client improved mentioned in #171
The output of `Ark -h` is now as follows
```
DESCRIPTION
ArkScript programming language
SYNOPSIS
Ark -h
Ark --version
Ark --dev-info
Ark -r
Ark ((<file> [-c]) | [-e <expression>]) [[-d]|-bcr] [-L <lib_dir>] [-f(fac|no-fac)] [-f(aitap|no-aitap)]
OPTIONS
-h, --help                  Display this message
--version                   Display ArkScript version and exit
--dev-info                  Display development information and exit
-r, --repl                  Run the ArkScript REPL
-c, --compile               Compile the given program to bytecode, but do not run
-e, --eval                  Evaluate ArkScript expression
-d, --debug...              Increase debug level (default: 0)
-bcr, --bytecode-reader     Launch the …
```

Add -e/--eval parameter to ArkScript client

---

CHANGELOG.md
examples/unbound.ark
include/Ark/Compiler/Compiler.hpp
include/Ark/Compiler/Compiler.inl
src/Compiler/Compiler.cpp

updating unbound variable checker to avoid throwing on plugin symbols

---

README.md

I made a small edit to Ark's README, including fixing my old GitHub username and a grammar mistake 😉

Readme: small edits

---

CHANGELOG.md
src/VM/VM.cpp

using a new plugin interface, more C-like

---

.github/workflows/ci.yml
include/Ark/VM/UserType.hpp
include/Ark/VM/inline/UserType.inl
src/VM/UserType.cpp
src/VM/VM.cpp

free usertypes when using keyword del

---

src/VM/VM.cpp

fixing Instruction::HEAD in the VM, otherwise clang hates it

---

README.md

Add Zsh and Fish support in installation script.

docs: Add more shells.

---

CONTRIBUTING.md

Will need to go over the code and check if everything was applied correctly

Adding naming conventions, enum class over enum

---

.github/workflows/linux-clang.yml
.github/workflows/linux-gcc.yml
.github/workflows/macos-clang.yml
.github/workflows/msvc.yml

Making a PR so that the CI runs
EDIT: it runs and works as intended, please merge

adding artifacts to our ci builds

---

.github/workflows/linux-clang.yml
.github/workflows/linux-gcc.yml
.github/workflows/msvc.yml
.github/workflows/release.yml

Ci release fix

---

src/Compiler/MacroProcessor.cpp

This should fix https://github.com/ArkScript-lang/std/pull/22

fixing macroprocessor so that we evaluate only what we can

---

include/Ark/Compiler/Node.hpp
include/Ark/Platform.hpp
include/Ark/VM/Closure.hpp
include/Ark/VM/Value.hpp

inline is ignored with using declspec(dllexport).
Please label hacktoberfest2021 :)

Fix compiler warnings

---

README.md

The link to the coding style document in the README was invalid. This might help new developers, myself included, during Hacktoberfest and/or otherwise.

Correct coding style link

---

.github/launch-tests
.github/workflows/ci.yml
CHANGELOG.md
CMakeLists.txt

Adding a valgrind job in the ci, checking for memory leaks.
Closes #349

ci: new step running valgrind to check for memory leaks

---

README.md

[Update the link to the documentation site](https://github.com/ArkScript-lang/Ark/pull/368#)
- [/] I have read the [Contributor guide](CONTRIBUTING.md)
- [/] My code follows the style guidelines of this project
- [/] I have commented my code, particularly in hard-to-understand areas
- [/] I have updated the documentation if needed
- [/] I have added tests that prove my fix/feature is working
- [/] New and existing tests pass locally with my changes

Update the link to the documentation site

---

README.md
examples/99bottles.ark
examples/ackermann.ark
examples/blockchain.ark
examples/callbacks.ark
examples/closures.ark
examples/counter.ark
examples/error.ark
examples/factorial.ark
examples/fibo.ark
examples/http.ark
examples/macros.ark
examples/more-or-less.ark
examples/quicksort.ark
examples/sum_digits.ark
tests/arkscript/async-tests.ark
tests/arkscript/builtins-tests.ark
tests/arkscript/list-tests.ark
tests/arkscript/macro-tests.ark
tests/arkscript/string-tests.ark
tests/arkscript/tests-tools.ark
tests/arkscript/unittests.ark
tests/arkscript/utf8-tests.ark
tests/arkscript/vm-tests.ark

Nothing complex, I was annoyed by the coding style which was C-like instead of Lisp-like and finally changed it. I may have forgotten things here and there.

fix: coding style
