ArkScript-lang/Ark

- src/main.cpp
This PR adds the CLI option `-c/--compile` which allows just the compilation of the program to bytecode, and not running it at the same time.
> Add -c/--compile CLI option to only compile the program and not run it.

- lib/Functional/Functional.ark
- tests/arithmetic-tests.ark
- tests/functional-tests.ark
This also forces the zip function to always return a list, as it would previously return `nil` if the lengths didn't match.
> Modified zip function to accept lists of different relative sizes

- lib/Functional/Reduce.ark
- tests/functional-tests.ark
Traditional reduce function in imperative languages (a left fold). The function takes a function -- which itself takes two arguments and returns one element -- and a list.
Then it successively applies the function to the elements in the list, for example with a function `sum` giving the sum of two elements: `(reduce sum [1 2 3 4])` is roughly equivalent to `(((1 + 2) + 3) + 4)`.
> Added reduce function

- lib/List/Product.ark
- tests/list-tests.ark
Similar behaviour to Sum for lists. The default is the neutral for multiplication, that is 1.
> Added Product function for Lists

- src/REPL/Repl.cpp
Also fixed brace style.
This would resolve #66.
As described in the expected behavior of the issue, it will just exit the REPL.
> Fixed problem where EOF would cause the REPL to infinitely loop.

- README.md
This pull request adds a note about building on macOS versions prior to 10.15, which was solved in issue #87. I tried to keep it as short as possible, to not clutter the documentation.
> Document building on macOS versions prior to 10.15

- Dockerfile
Reduced 456MB to 449MB.
Inspired by the discussion from #148. Can we make it even smaller? What does `cmake --install build --config Release` actually do?
> Use only necessary files for installation in Dockerfile

- src/Compiler/Lexer.cpp
#159 Previously saved_line and saved_char were only set at the start of string literals. They should also be set at the start of identifiers, numbers and operators. 
Other issue is that the variable character is set to 0 when a newline character is reached but is incremented at the bottom of the loop, meaning that the first character of the line ends up being 1. Fixed by adding a continue to shortcircuit the loop.
> Fix error messages #159

- include/Ark/Compiler/Compiler.hpp
- src/Compiler/Compiler.cpp
#144 Does a simple scan of all variables defined using Let, Mut or as function arguments, and checks for any symbols used that do not fall under those. This can help catch simple typos earlier. 
For source code (`a.ark`): 
```
(let b 10)
(print bb)
```
Output for `Ark a.ark -c` is:  
```
CompilationError: unbound variable: bb (symbol is used but not defined)
[ Error ] Ark::State.doFile(../a.ark) failed
```
> Check for possible unbound variables at compile time

- CHANGELOG.md
- src/Compiler/Compiler.cpp
- src/Compiler/Parser.cpp
Now let/mut/set only accepts 2 arguments or a chain of one identifier + dot expressions (e.g. `(let a b.c.d)`)
Closes #197
> Fix let/mut/set which could accepts more than 2 arguments

- README.md
Previous markdown translated to a relative path. In theory you could prepend a / but that doesn't work if the README is rendered on another site (via an aggregate site or something of the sort).
The simplest solution was just to remove the link syntax altogether as URI-like text is rendered as an anchor tag by default in most Markdown implementations (including Github's).
> Fix the benchmarks link

- .gitignore
- include/Ark/Compiler/BytecodeReader.hpp
- src/Compiler/BytecodeReader.cpp
Add parameters to the `display` method of the `BytecodeReader` class. (See issue: #158)
> Add arguments to the bytecode reader

- src/arkscript/REPL/Repl.cpp
This PR Closes #305
Here is a technical description of the main cause of the problem and the solution.
Here are the steps taken when an INCORRECT command is entered by the user
1. The method doString() is called as follows:
`if (state.doString(tmp_code.str()))`
2. The incorrect command goes along with the methods until an EXCEPTION is called to throw an error as follows:
`catch (const std::exception& e)
{
std::printf("%s\n", e.what());
return false;
}`
3. So, the body of if() statement is now neglected and the else part is executed as follows:
`std::printf("Ark::State::doString failed");`
This causes the error message to be appended at the beginning of the next command output (whether it was a correct or incorrect command).
Replacing printf() with cout resolved the issue and now the error …
> Replaced printf() with cout()

- src/arkscript/REPL/Repl.cpp
This PR Closes #304 
The input() method presented in the line `char const* buf = m_repl.input(prompt);` can only return a **nullptr** in two specific cases:
1. Ctrl + C is pressed
2. Ctrl + D is pressed
We just need the REPL to exit when (CTRL + D) is pressed.
So, the only difference between the 2 key bindings would be the value assigned **errno**. As for (Ctrl + C) key binding, we would expect **errno** to be set to **EAGAIN**. Thus, checking for these two conditions assure that (Ctrl + D) was pressed and closes the REPL.
Side Note: I checked my logic against the implemented examples in **replxx** repository and the same approach has been followed to check for (Ctrl + D) and differentiate between its return value and that of (Ctrl + C) key binding.
> Handled (Ctrl+D) key binding

- src/arkreactor/Compiler/Parser.cpp
This PR Closes #276
This change is intended to check the tokens prior to Keywords to detect whether any is unexpected.
So, for keywords, a parsing algorithm is handled for each using the following methods:
```cpp
if (token.token == "if")
fun_ptr = &Parser::parseIf;
else if (token.token == "let" || token.token == "mut")
fun_ptr = &Parser::parseLetMut;
else if (token.token == "set")
fun_ptr = &Parser::parseSet;
else if (token.token == "fun")
fun_ptr = &Parser::parseFun;
else if (token.token == "while")
fun_ptr = &Parser::parseWhile;
else if (token.token == "begin")
fun_ptr = &Parser::parseBegin;
else if (token.token == "import")
fun_ptr = &Parser::parseImport;
else if (token.token == "quote")
fun_ptr = &Parser::parseQuote;
else if (token.token == "del")
fun_ptr = &Parser::parseDel;
``` …
> Added extra checks for the parser

- .gitmodules
- include/Ark/Compiler/Macros/Executor.hpp
- include/Ark/VM/Plugin.hpp
- include/Ark/VM/Scope.hpp
- include/Ark/VM/UserType.hpp
- include/Ark/VM/VM.hpp
- include/Ark/VM/Value.hpp
- include/Ark/VM/inline/UserType.inl
- include/Ark/VM/inline/VM.inl
- src/arkreactor/Compiler/AST/Parser.cpp
- src/arkreactor/Compiler/Compiler.cpp
- src/arkreactor/VM/Scope.cpp
- src/arkreactor/VM/UserType.cpp
- src/arkreactor/VM/VM.cpp
- src/arkreactor/VM/Value.cpp
- tests/cpp/03.cpp
Fixed a potential bug with `UserType` where user supplied data could be deleted in one object when it is still potentially being used by another object (because the original object was copied).
Fixed a couple of other issues with move semantics (to make it work correclty)
> Fix move semantics

- README.md
- src/arkscript/main.cpp
Hi again :) It's been a while. I was just messing around with the project again when I noticed that you'll receive deprecation warnings if you use `ark`; yet the output of the "--help" command still shows all the commands using the old `ark` program name. This PR fixes that that by changing the name of the executable on the help screen to be `arkscript`.
> Change clipp program name

- CONTRIBUTING.md
Before running the test suite, the console module at the very least
needs to be compiled. This adds a note about building the modules before
running the test suite.
Additionally, I updated the path for the ArkScript test suite (the
correct path is `tests/arkscript/unittests.ark`).
I've also updated the name of the executable to be `arkscript` so users
do not get the deprecation warning when copying/pasting the command.
Finally, I noticed that there's a note about running the standard library
test suite using the `tests/all.ark` file, but I actually don't see that 
in the project. Is there a way to generate that file? I think I might be
missing something as I don't have that file in my project and I don't see
it here in the repo.
> CONTRIBUTING: Include note about building modules for test suite

- CHANGELOG.md
- README.md
- src/arkscript/main.cpp
We can now give multiple paths to --lib when using the CLI.
> Fixing issue 379: giving multiple paths to --lib

- CHANGELOG.md
- include/Ark/TypeChecker.hpp
- include/Ark/VM/VM.hpp
- include/Ark/VM/inline/VM.inl
- src/arkreactor/TypeChecker.cpp
Changing the way we count received arguments in arity / type errors for failed function call. The stack now returns a `Value(ValueType::Undefined)` when it's empty (as a failsafe) instead of Nil. The typechecker takes this in account to generate error messages accordingly.
> fix: the error message should always display the correct number of arguments it received

- CHANGELOG.md
- CMakeLists.txt
Adding IPO/LTO support when building, if the compiler can provide it.
> build: adding link time optimization support

- CHANGELOG.md
- src/arkreactor/Compiler/Macros/Processor.cpp
- tests/arkscript/macro-tests.ark
The macro processor should always run, even if they aren't any user defined macros. Also, argcount now checks for the type of the passed node to prevent crashes (it was assuming everything was a symbol). It will work with both symbols and anonymous functions.
Closes #383
> Macros should always be evaluated and argcount has to work with both Symbols and anonymous Functions

- include/termcolor/proxy.hpp
- src/arkreactor/Compiler/AST/Node.cpp
- src/arkreactor/Compiler/AST/makeErrorCtx.cpp
- src/arkreactor/Compiler/BytecodeReader.cpp
- src/arkreactor/TypeChecker.cpp
- src/arkreactor/VM/State.cpp
- src/arkreactor/VM/VM.cpp
- src/arkscript/main.cpp
Now including termcolor through a proxy header.
> fix: adding a proxy header for termcolor to avoid errors on errors due to Windows

- CHANGELOG.md
- CMakeLists.txt
- include/Ark/Compiler/AST/Lexer.hpp
- include/Ark/Compiler/BytecodeReader.hpp
- include/Ark/Compiler/Compiler.hpp
- include/Ark/Compiler/JsonCompiler.hpp
- include/Ark/Compiler/Macros/Executor.hpp
- include/Ark/Compiler/Macros/Processor.hpp
- include/Ark/REPL/Repl.hpp
- include/Ark/Utils.hpp
- include/Ark/VM/Value.hpp
- src/arkreactor/Builtins/IO.cpp
- src/arkreactor/Compiler/AST/Lexer.cpp
- src/arkreactor/Compiler/AST/Parser.cpp
- src/arkreactor/Compiler/BytecodeReader.cpp
- src/arkreactor/Compiler/Compiler.cpp
- src/arkreactor/Compiler/JsonCompiler.cpp
- src/arkreactor/Compiler/Macros/Executor.cpp
- src/arkreactor/Compiler/Macros/Processor.cpp
- src/arkreactor/TypeChecker.cpp
- src/arkreactor/VM/State.cpp
- src/arkreactor/VM/VM.cpp
- src/arkscript/REPL/Repl.cpp
- src/arkscript/main.cpp
Removes std::cout/std::cerr/std::printf and uses fmt::print almost everywhere (if possible).
Closes #248
> chore: updating the logging strategy (streams/printf removed, using fmt::print)
